package tech.janhoracek.debtdragon.utility

object Constants {
    const val PASSWORD_LENGTH = 6

    const val DATABASE_REQUESTS = "Requests"
    const val DATABASE_FRIENDSHIPS = "Friendships"
    const val DATABASE_GROUPS = "Groups"
    const val DATABASE_NAMES_GROUP_PROFILE_IMAGE = "groupImage.jpg"
    const val DATABASE_DEBTS = "Debts"
    const val DATABASE_USERS = "Users"
    const val DATABASE_USER_NAME = "name"
    const val DATABASE_USER_IMG_URL = "url"
    const val DATABASE_USER_EMAIL = "email"
    const val DATABASE_USER_UID = "uid"
    const val DATABASE_DEBT_PAYER = "payer"
    const val DATABASE_DEBT_CATEGORY_FOOD = "food"
    const val DATABASE_DEBT_CATEGORY_ENTERTAINMENT = "entertainment"
    const val DATABASE_DEBT_CATEGORY_FINANCE= "finance"
    const val DATABASE_DEBT_CATEGORY_FASHION = "fashion"
    const val DATABASE_DEBT_CATEGORY_ELECTRONIC = "electronics"
    const val DATABASE_DEBT_CATEGORY_OTHER = "other"
    const val DATABASE_DEBT_CATEGORY_PAYMENT = "payment"
    const val DATABASE_NAMES_DEBT_PROFILE_IMAGE = "debtImage.jpg"
    const val DATABASE_DEBTS_VALUE = "value"
    const val DATABASE_DEBTS_CATEGORY = "category"
    const val DATABASE_BILL = "Bills"
    const val DATABASE_BILL_NAME = "name"
    const val DATABASE_BILL_PAYER = "payer"
    const val DATABASE_BILL_ID = "id"
    const val DATABASE_BILL_TIMESTAMP = "timestamp"
    const val DATABASE_GROUPDEBT = "GDebts"
    const val DATABASE_GROUPDEBT_VALUE = "value"
    const val DATABASE_GROUPDEBT_DEBTOR = "debtor"
    const val DATABASE_GROUPDEBT_PAYER = "payer"
    const val DATABASE_GROUPS_MEMBERS = "members"
    const val DATABASE_GROUPS_STATUS = "calculated"
    const val DATABASE_GROUPS_STATUS_LOCKED = "locked"
    const val DATABASE_GROUPS_STATUS_CALCULATED = "calculated"
    const val DATABASE_PAYMENT = "Payments"
    const val DATABASE_PAYMENT_ID = "id"
    const val DATABASE_PAYMENT_RESOLVED = "resolved"

}